FROM debian:stable
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        systemd systemd-sysv dbus dbus-user-session && \
    rm -rf /var/lib/apt/lists/*
CMD ["/sbin/init"]
