name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  DEPS_APT: curl gcc clang libudev-dev libgbm-dev libxkbcommon-dev libegl1-mesa-dev libwayland-dev libinput-dev libdbus-1-dev libsystemd-dev libseat-dev libpipewire-0.3-dev libpango1.0-dev libdisplay-info-dev

jobs:
  test:
    name: test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
        with:
          show-progress: false

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y $DEPS_APT

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Build tests
        run: cargo test --no-run --all --exclude jiji-visual-tests

      - name: Test
        run: cargo test --all --exclude jiji-visual-tests -- --nocapture
